### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by LuisCarlosPallaresAscanio** [mahart-studio/kivystudio#21]
[WARNING] Parser: File "<inline>", line 26:
...
     24:            on_size: Clock.schedule_once(lambda dt: setattr(self, 'grid_len', int(self.width/(self.children[0].width+10))), 1)
     25:
>>   26:[StudioFileThumbEntry@IconWidget_]:
     27:    image: image
     28:    locked: False

     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "<string>", line 24, in <lambda>
 IndexError: list index out of range

**Comment by mcroni** [comment]
this issue has been fixed, please try pulling the current build

**Comment by paaKways** [comment]
Hey there!

I just saw this. I actually pulled much recently than 22 days ago when LuisCarlos had this issue but im still having this issue

self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "<string>", line 24, in <lambda>
 IndexError: list index out of range

**Comment by mcroni** [comment]
if you just want an emulator , you can use  this [`kivyEmu`](https://github.com/mcroni/KivyLiteEmulator) whilst we continue to work on kivystudio

**Comment by avour** [comment]
@mcroni the KivyEmu is a really nice project. love it

**Comment by avour** [comment]
@LuisCarlosPallaresAscanio 
it seems i have seen the list out of range error before.
can you state your system specs, the python version and your window provider

**Comment by LuisCarlosPallaresAscanio** [comment]
Windows 7
Python 3.6

**Comment by LuisCarlosPallaresAscanio** [comment]
[WARNING] Parser: File "<inline>", line 26:
...
     24:            on_size: Clock.schedule_once(lambda dt: setattr(self, 'grid_len', int(self.width/(self.children[0].width+10))), 1)
     25:
>>   26:[StudioFileThumbEntry@IconWidget_]:
     27:    image: image
     28:    locked: False
...
Deprecated Kivy lang template syntax used "[StudioFileThumbEntry@IconWidget_]". Templates will be removed in a future version
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "X:\P\Programacion\Python\Pruebas\GUI\Kivy\Dependencias\kivystudio\build\lib\kivystudio\main.py", line 47, in <module>
     studio_app.run()
   File "C:\Users\Compaq\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\Compaq\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\Compaq\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\Compaq\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\Compaq\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\base.py", line 339, in idle
     Clock.tick()
   File "C:\Users\Compaq\AppData\Local\Programs\Python\Python36\lib\site-packages\kivy\clock.py", line 591, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "<string>", line 24, in <lambda>
 IndexError: list index out of range

**Comment by mcroni** [comment]
this is really strange

**Comment by LuisCarlosPallaresAscanio** [comment]
Maybe it's a mistake on my part, tell me one step at a time, the strange thing is that sometimes a moment works

**Comment by avour** [comment]
Did you set it up with the setup.py, cause i think that's what causing the
issue the setup.py still has some setuo issues, try unistalling it and
running main.py in the kivystudio directory

**Comment by LuisCarlosPallaresAscanio** [comment]
--Did you set it up with the setup.py, cause i think that's what causing the issue the setup.py still has some setuo issues, try unistalling it and running main.py in the kivystudio directory.

install it with setup.py and then run main.py

**Comment by mahart-studio** [comment]
try pip install kivystudio,
pull from the mahart-studio repo
and run main.py

**Comment by rajat45mishra** [comment]
for python3 replace super(KivyStudio, self).run() in main.py to super().run() then build and run work like charm

**Comment by mahart-studio** [comment]
Hi, that's would work well like you said,
But would also break support for python2,
By the way it's seems you know your stuff. Would you mind contributing to
this project.
